### ISSUE TITLE
Gene annotation

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/Live-seq#2]
What's the difference between data/mouseGeneTable87_mCherry_EGFP.txt and data/Mus_musculus.GRCm38.100_data.annot.txt ?
Which one was used in the end? Why two versions ?

**Comment by zouter** [comment]
I'm also unsure about this. It seems Mus_musculus.GRCm38.100_data.annot.txt is only used by @PernilleYR in 7 ?

**Comment by zouter** [comment]
Pernille used some earlier versions for her analysis, while Wanze used the one he used from the start. I think it's ok for reproducibility to keep both
