### ISSUE TITLE
Cell metadata

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/Live-seq#4]
There are two files:
- InfoContent_Updated_VX-ASPC-9_4.csv
- meta.final.csv

Why two files? What is the difference?

**Comment by zouter** [comment]
Not sure to be honest. Maybe @WanzeChen  can comment

**Comment by zouter** [comment]
InfoContent_Updated_VX-ASPC-9_4.csv contains metadata on extracted volume, used for one figure. I decided to keep it as is
