### ISSUE TITLE
Missing s.genes.mouse.rds

### ISSUE THREAD

**Issue by zouter** [DeplanckeLab/Live-seq#5]
https://github.com/DeplanckeLab/Live-seq/blob/d1f99ce4ae9a8d4d3fbda4d8328e9057cfa8daac/05_Liveseq_with_LiveCell_imaging/5_Liveseq_with_LiveCell_imaging.R#L220

**Comment by zouter** [comment]
Hi @WanzeChen , I can't seem to find the functions to get these genes

**Comment by VincentGardeux** [comment]
Found it.
