### ISSUE TITLE
Missing scRNAseq_only.rds

### ISSUE THREAD

**Issue by zouter** [DeplanckeLab/Live-seq#6]
https://github.com/DeplanckeLab/Live-seq/blob/d1f99ce4ae9a8d4d3fbda4d8328e9057cfa8daac/06_Clustering/6_Clustering_and_accuracy.R#L33

@PernilleYR Do you know where these files are created?

**Comment by zouter** [comment]
Working on fixing it now

**Comment by VincentGardeux** [comment]
3_scRNAseq_only.R seems to create a file 
`saveRDS(scRNA  ,"03_scRNA_seq_only/scRNAseq.rds")`

So it could be this one, that was renamed afterwards?

**Comment by zouter** [comment]
Indeed, thanks!
